spring:
  application:
    name: ecommerce-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ seu banco
    username: postgres
    password: senha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method